Imported Upstream version 1.4.2~dfsg

diff --git a/contrib/scripts/safe_asterisk b/contrib/scripts/safe_asterisk
--- a/contrib/scripts/safe_asterisk
+++ b/contrib/scripts/safe_asterisk
@@ -10,7 +10,6 @@ MACHINE=`hostname`			# To specify which machine has crashed when getting the mai
 DUMPDROP=/tmp
 SLEEPSECS=4
 ASTSBINDIR=__ASTERISK_SBIN_DIR__
-ASTPIDFILE=__ASTERISK_VARRUN_DIR__/asterisk.pid
 
 # comment this line out to have this script _not_ kill all mpg123 processes when
 # asterisk exits
@@ -26,21 +25,13 @@ PRIORITY=0
 # set to the system's maximum files open devided by two, if not set here.
 # MAXFILES=32768
 
-# Check if Asterisk is already running.  If it is, then bug out, because
-# starting safe_asterisk when Asterisk is running is very bad.
-VERSION=`${ASTSBINDIR}/asterisk -rx 'core show version'`
-if [ "`echo $VERSION | cut -c 1-8`" = "Asterisk" ]; then
-	echo "Asterisk is already running.  $0 will exit now."
-	exit 1
-fi
-
 # since we're going to change priority and open files limits, we need to be
 # root. if running asterisk as other users, pass that to asterisk on the command
 # line.
 # if we're not root, fall back to standard everything.
 if [ `id -u` != 0 ]
 then
-	echo "Oops. I'm not root. Falling back to standard prio and file max." >&2
+	echo "Ops. I'm not root. Falling back to standard prio and file max." >&2
 	echo "This is NOT suitable for large systems." >&2
 	PRIORITY=0
 else
@@ -105,11 +96,6 @@ if [ ! -w ${DUMPDROP} ]; then
 fi
 
 #
-# Don't die if stdout/stderr can't be written to
-#
-trap '' PIPE
-
-#
 # Run scripts to set any environment variables or do any other system-specific setup needed
 #
 
@@ -128,10 +114,10 @@ run_asterisk()
 		if [ "$TTY" != "" ]; then
 			cd /tmp
 			stty sane < /dev/${TTY}
-			nice -n $PRIORITY ${ASTSBINDIR}/asterisk -f ${CLIARGS} ${ASTARGS} >& /dev/${TTY} < /dev/${TTY}
+			nice -n $PRIORITY ${ASTSBINDIR}/asterisk ${CLIARGS} ${ASTARGS} >& /dev/${TTY} < /dev/${TTY}
 		else
 			cd /tmp
-			nice -n $PRIORITY ${ASTSBINDIR}/asterisk -f ${CLIARGS} ${ASTARGS}
+			nice -n $PRIORITY ${ASTSBINDIR}/asterisk ${CLIARGS} ${ASTARGS}
 		fi
 		EXITSTATUS=$?
 		echo "Asterisk ended with exit status $EXITSTATUS"
@@ -149,21 +135,18 @@ run_asterisk()
 			if [ "$EXEC" != "" ]; then
 				$EXEC
 			fi
-
-			PID=`cat ${ASTPIDFILE}`
-			if [ -f /tmp/core.${PID} ]; then
-				mv /tmp/core.${PID} ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
-			elif [ -f /tmp/core ]; then
+			if [ -f /tmp/core ]; then
 				mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
 			fi
 		else
-			echo "Asterisk died with code $EXITSTATUS."
-
-			PID=`cat ${ASTPIDFILE}`
-			if [ -f /tmp/core.${PID} ]; then
-				mv /tmp/core.${PID} ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
-			elif [ -f /tmp/core ]; then
-				mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
+			if [ "${EXITSTATUS}" = "0" ]; then
+				echo "Asterisk ended normally.  Aborting."
+				exit 0
+			else
+				echo "Asterisk died with code $EXITSTATUS."
+				if [ -f /tmp/core ]; then
+					mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
+				fi
 			fi
 		fi
 		echo "Automatically restarting Asterisk."
